Repository weka/csi-wekafs, pull requests merged in 2023-06, with the labels that each got.

#116 feat(CSI-67): sign helm chart
  .github/workflows/pull-request.yaml
  .github/workflows/push-dev.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
  README.md.gotmpl
  charts/csi-wekafsplugin/.helmignore
  charts/csi-wekafsplugin/CHANGELOG.md
  charts/csi-wekafsplugin/Chart.yaml
  charts/csi-wekafsplugin/LOCAL.md
  charts/csi-wekafsplugin/README.md
  charts/csi-wekafsplugin/README.md.gotmpl
  charts/csi-wekafsplugin/templates/NOTES.txt
  charts/csi-wekafsplugin/templates/controllerserver-clusterrole.yaml
  charts/csi-wekafsplugin/templates/controllerserver-clusterrolebinding.yaml
  charts/csi-wekafsplugin/templates/controllerserver-role.yaml
  charts/csi-wekafsplugin/templates/controllerserver-rolebinding.yaml
  charts/csi-wekafsplugin/templates/controllerserver-serviceaccount.yaml
  charts/csi-wekafsplugin/templates/controllerserver-statefulset.yaml
  charts/csi-wekafsplugin/templates/driver.yaml
  charts/csi-wekafsplugin/templates/nodeserver-clusterrole.yaml
  charts/csi-wekafsplugin/templates/nodeserver-clusterrolebinding.yaml
  charts/csi-wekafsplugin/templates/nodeserver-daemonset-selinux.yaml
  charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
  charts/csi-wekafsplugin/templates/nodeserver-serviceaccount.yaml
  charts/csi-wekafsplugin/values.schema.json
  charts/csi-wekafsplugin/values.yaml
  deploy/util/cleanup-wekafs.sh
  deploy/util/deploy-wekafs.sh
Labels: feature

#118 Version 2.1.0 content
  .github/workflows/lint_pr.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/push-dev.yaml
  .github/workflows/release.yaml
  .github/workflows/renovate_jira.yaml
  .github/workflows/sanity.yaml
  Makefile
  README.md
  README.md.gotmpl
  charts/csi-wekafsplugin/.helmignore
  charts/csi-wekafsplugin/CHANGELOG.md
  charts/csi-wekafsplugin/Chart.yaml
  charts/csi-wekafsplugin/LOCAL.md
  charts/csi-wekafsplugin/README.md
  charts/csi-wekafsplugin/README.md.gotmpl
  charts/csi-wekafsplugin/templates/NOTES.txt
  charts/csi-wekafsplugin/templates/controllerserver-clusterrole.yaml
  charts/csi-wekafsplugin/templates/controllerserver-clusterrolebinding.yaml
  charts/csi-wekafsplugin/templates/controllerserver-role.yaml
  charts/csi-wekafsplugin/templates/controllerserver-rolebinding.yaml
  charts/csi-wekafsplugin/templates/controllerserver-serviceaccount.yaml
  charts/csi-wekafsplugin/templates/controllerserver-statefulset.yaml
  charts/csi-wekafsplugin/templates/driver.yaml
  charts/csi-wekafsplugin/templates/nodeserver-clusterrole.yaml
  charts/csi-wekafsplugin/templates/nodeserver-clusterrolebinding.yaml
  charts/csi-wekafsplugin/templates/nodeserver-daemonset-selinux.yaml
  charts/csi-wekafsplugin/templates/nodeserver-daemonset.yaml
  charts/csi-wekafsplugin/templates/nodeserver-serviceaccount.yaml
  charts/csi-wekafsplugin/values.schema.json
  charts/csi-wekafsplugin/values.yaml
  deploy/util/cleanup-wekafs.sh
  deploy/util/deploy-wekafs.sh
  go.mod
  go.sum
  semicolon_delimited_script
Labels: ignore-semantic-pull-request

#131 fix(CSI-118): cannot initialize API client with non-root organization
  pkg/wekafs/wekafs.go
Labels: fix
